# Generated by Django 2.2 on 2022-10-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='My_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='image_covers', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
