# Generated by Django 2.2 on 2022-10-09 17:24

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('ns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_image',
            name='disclaimer',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_covers_disclaimer', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='my_image',
            name='cover',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_covers', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
